language: python
python:
  - "2.7"
addons:
  apt:
    packages:
     - gdal-bin
     - python-gdal
virtualenv:
  system_site_packages: true
install:
 - pip install -r requirements.txt
 - npm install
script:
 - python test_model.py
 - npm run build:deps
